---
title: "FAQ"
---

#### How do I sign up?

Registration has closed for the 2025 Triangle Sports Analytics Challenge.
<!-- Register [here](https://forms.gle/PCqbq2rrjqR9ByMX8).  -->

If you have any questions about your registration, please contact [Prof. Alexander Fisher](mailto:aaf29@duke.edu).


#### Who is eligible to compete?

For the 2025 Triangle Sports Analytics Challenge, only current undergraduate and master's students at Duke, UNC, Chapel Hill and North Carolina State University are eligible to compete.

#### Is there a registration fee?

No.

#### What do I need to compete?

Register for the event and submit predictions and confidence intervals by the deadline making sure you are following all of the instructions on the [Task](/task) page. A computer with R or Python and a basic background with linear models is ideal. 

#### Is there a prize for the winners?

At this current point in time, there is no prize for the winners. This could change but there is no guarantee. This is an excellent, exciting opportunity to build your resume with essential data science skills. The photos of the winning teams in each category  will be displayed on this website as long as this competition exists. 

#### Other questions

For all other questions, please reach out to your school's coordinator:

|                      |                                 |                                                          |
|----------------------|---------------------------------|----------------------------------------------------------|
| Dr. Alexander Fisher | Duke                            | [aaf29\@duke.edu](mailto:aaf29@duke.edu)                 |
| Dr. Mario Giacomazzo | UNC, Chapel Hill                | [mgiacoma\@email.unc.edu](mailto:mgiacoma@email.unc.edu) |
| Dr. Elijah Meyer     | North Carolina State University | [esmeyer2\@ncsu.edu](mailto:esmeyer2@ncsu.edu)   |
