---
title: "Challenge: Interval"
---

### Objective

Construct  `prediction intervals` for the point spread of 88 ACC basketball games in the current NCAA Men's basketball season. 

### Instructions

1.  Download a copy of the Google Sheet [here](https://docs.google.com/spreadsheets/d/1-NJjX7W1ztloGJShjclTPFQ452qBt9hWPdXTVbRwYc8/edit?usp=sharing). Click `File`, `Download`, `Comma Separated Values (.csv)` to download your prediction spreadsheet as a `csv` to your computer.

2.  **Only edit cells that contain NA.** All the information in the first three columns should not be altered at all. The games should remain in their original order. Your predictions may not be considered if you alter the information in these first three columns. Keep them in the games in their original order.

::: callout-important
-   Enter the lower bound of the interval in the `ci_lb` column.
-   Enter the upper bound of the interval in the `ci_ub` column.
-   Prediction intervals must be numeric values. They do not need to be integers. For example, you may predict the point spread to be somewhere between -8.25 and 3.75 points.
-   Insert your team name in the first cell of the `team_name` column.
-   Insert the names of all the students on your team in the `team_members` column. This includes the name of the person who submitted. If you are submitting solo, this column should only have your name in the column.
- Make sure that you have prediction intervals for all 88 college basketball games. We cannot consider your predictions if there are still missing values.
:::

3.  Rename the original file to include your **team name**. Do this by replacing the word "template" in the original file name. For example, if your team name is *Shot Callers*, then your file name should be "tsa_ci_Shot_Callers_2026".  Upload your file as a `csv` to the dropbox link [here](https://www.dropbox.com/request/3rRzJVPdjfrjywYuXSm0). **Submission of this is due by midnight on January 30, 2026.** Submissions after midnight will not be considered at all.

4. Submit a one-page (maximum) write-up detailing *how* you constructed your prediction intervals e.g. what method are you using, how did you evaluate your chosen method. If your team also submitted predicted point spread, you don't need to submit two files. Just submit one file that includes rationale behind your point spreads and prediction intervals.  Please upload this as a `.pdf` or `.docx` document [here](https://www.dropbox.com/request/3rRzJVPdjfrjywYuXSm0). Be sure to rename your file to the name of your team. **Submission of this is due by midnight on January 30, 2026.** 


### Evaluation

Your prediction intervals for the point spread will be evaluated by a new metric based on your interval widths abbreviated $PIW$. Remember that smaller intervals are better since they are more precise; however, you don't want to be reporting intervals that rarely contain the true point spread. Details about $PIW$ is found below:

<p style="margin-left: 25px;">
In order for your prediction intervals to be considered, **at least 70%** of your intervals must contain the true spread. Given this criteria, we heavily recommend reporting intervals with a minimum of 70% coverage. We also recommend testing your methodology on past data to check coverage.
</p>

$$
PIW = \begin{cases}
    \frac{1}{n} \sum_{i=1}^n \left| ub_i - lb_i \right|,& \text{if Coverage} \geq 70\% \\
    & \\
    \text{Disqualified (DQ)},              & \text{if Coverage} < 70\%
\end{cases}
$$ 
<p style="margin-left: 25px;">
where $ub_i$ is the upper bound of your interval and $lb_i$ is the lower bound of your interval for the spread of the $i$th game. The average is taken over all $n = 42$ total games for which you are producing prediction intervals. In words, the $PIW$ is the average width of all your confidence intervals. Smaller $CIW$ indicates more precise confidence intervals.
</p>

### Future Scoreboard

**This is where you will go later to check your standing in the competition.**