---
title: "Challenge: Spread"
---

### Objective

Predict `point spread` together with an `interval` (confidence/prediction) in the 2025 NCAA conference games for Duke, NC State and UNC.

### Instructions

1.  Download a copy of the google sheet [here](https://docs.google.com/spreadsheets/d/1jIMwfPQj6GiPVYAi7N4hu2YQS2GhbNlmz5OA6Z7a65w/edit?gid=0#gid=0). Click `File`, `Download`, `Comma Separated Values (.csv)` to download your prediction spreadsheet as a `csv` to your computer.

2.  **Only edit cells that contain NA.** All the information in the first three columns should not be altered at all. The games should remain in their original order. Your predictions may not be considered if you alter the information in these first three columns. Keep them in the games in their original order.

::: callout-important
-   Enter your predicted point spread (home team minus away team) in the `pt_spread` column.
-   Point spreads must be numeric values. They do not need to be integers. For example, you may predict the point spread to be -12.347 points.
-   Insert your team name in the first cell of the `team_name` column.
-   Insert the names of all the students on your team in the `team_members` column. This includes the name of the person who submitted. If you are submitting solo, this column should only have your name in the column.
- Make sure that you have point spreads for all 88 college basketball games. We cannot consider your predictions if there are still missing values.
:::

3.  Rename the original file to include your **team name**. Do this by replacing the word "template" in the original file name. For example, if your team name is *Shot Callers*, then your file name should be "tsa_pt_spread_Shot_Callers_2026".  Upload your file as a `csv` to the dropbox link [here](https://www.dropbox.com/request/3rRzJVPdjfrjywYuXSm0). **Submission of this is due by midnight on January 30, 2026.** Submissions after midnight will not be considered at all.

4. Submit a one-page (maximum) write-up detailing *how* you predicted the point spread e.g. what type of model are you using, how did you evaluate your model, what variables are involved? Please upload this as a `.pdf` or `.docx` document [here](https://www.dropbox.com/request/3rRzJVPdjfrjywYuXSm0). Be sure to rename your file to the name of your team. **Submission of this is due by midnight on January 30, 2026.** 

### Evaluation

Your predicted point spreads will be evaluated by the classic metric, mean absolute error ($MAE$). This metric is defined below:

$$
MAE = \frac{1}{n} \sum_{i=1}^n \left| \mu_i - \hat{\mu}_i \right|
$$

<p style="margin-left: 25px;">
where $\mu_i$ is the actual point spread outcome (home - away points) and $\hat{\mu}_i$ is your predicted point spread for the $i$th game. The average is taken over all $n = 42$ total games for which you are predicting the outcome. In words, the $MAE$ is the average number of points your predictions are away from the truth. Smaller $MAE$ indicates accurate point predictions.
</p>

### Future Scoreboard

**This is where you will go later to check your standing in the competition**